[package]
name = "desynced-exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "=1.*"
flate2 = "=1.*"
serde = { version = "=1.*", features = ["derive"]}

[dev-dependencies]
ron = { version = "=0.8.*" }
serde_json = { version = "=1.*" }

