[package]
name = "exchange-desynced-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.*"
exchange-desynced = { path = ".." }
serde = { version = "=1.*"}
ron = { version = "=0.8.*" }

